# Create a GitHub action to email a report from a file at 6 a.m. daily.
name: Send Report Email
on:
  schedule:
    - cron: '0 6 * * *'
jobs:
  email_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Send email
        run: |
          cat report.txt | mail -s "Daily Report"